services:
  hugo:
    image: klakegg/hugo:0.111.3-pandoc
    command:
     - -c
     - |
       #!/bin/bash
       set -e
       set -x
       which git || apk add git
       
       sed -i -r "s/(^name = \".*fa-github.*) [0-9]+\.[0-9]+\.[0-9]+[^\"]*\"/\1 `git describe --tags`\"/g" config.toml
       cat config.toml | grep fa-github
       
       sed -i -r  "s#(^url = \".*/tree)/[0-9a-f]{40}[^\"]*\"#\1/`git rev-parse HEAD`\"#g" config.toml
       cat config.toml| grep '/tree/'
       
       hugo server --debug --templateMetrics

    entrypoint: /bin/bash
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
